### ISSUE TITLE
AccountMenu strange display

### ISSUE THREAD

**Issue by yoannfleurydev** [HugoPerard/standup-app#17]
**Describe the bug**
The display of the AccountMenu is sliced by the meet button.

**To Reproduce**
1. Connect on the application
2. Click on the "avatar"
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/3920615/126300050-74b5b915-524e-4809-9ef5-c31f8ab07520.png)

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Browser Chrome Latest

**Comment by HugoPerard** [comment]
Thanks you for this issue.
I just push a fix, it will be deploy soon. I wait for a quick test and I will close this issue

**Comment by yoannfleurydev** [comment]
Looks good to me. I'm closing this.

![bitmoji](https://sdk.bitmoji.com/render/panel/c01f75cb-46fb-48c6-b217-e765d364b6c9-28509fbe-5dd0-4c1e-9b9f-5043673dc433-v1.png?transparent=1&palette=1&width=246)
