### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by HugoPerard** [HugoPerard/standup-app#2]
**Is your feature request related to a problem? Please describe.**
Colors are set in each components of the app and are difficult to maintain

**Describe the solution you'd like**
Define dark mode and put it at default

**Comment by yoannfleurydev** [comment]
![image](https://user-images.githubusercontent.com/3920615/131568397-e56e84ed-eb2f-4cb7-87e4-e0491165df64.png)

In light mode, checkboxes are not visible

**Comment by HugoPerard** [comment]
Thanks for your feedback, I just push a fix
