### ISSUE TITLE
We should be able to remove people that left the company from the /app/offices page.

### ISSUE THREAD

**Issue by yoannfleurydev** [HugoPerard/standup-app#24]
**Is your feature request related to a problem? Please describe.**

When people are leaving the BearStudio, their data are still in the `/app/offices`. We should be able to remove them because they won't open the page again to change the data.

**Describe the solution you'd like**
A clickable cross with a confirmation popover so we do not remove people that are still in the company.

**Comment by HugoPerard** [comment]
I just add a new feature for this. A button for clear presences of all offices.
I put this issue at "To test" waiting for feedbacks
