### ISSUE TITLE
On mobile, the menu is not visible

### ISSUE THREAD

**Issue by yoannfleurydev** [HugoPerard/standup-app#31]
![Screenshot_20210916-235935.jpg](https://user-images.githubusercontent.com/3920615/133691523-fce8511f-ff11-41da-a9d5-7e089bf8a7f2.jpg)

![Screenshot_20210917-000045.jpg](https://user-images.githubusercontent.com/3920615/133691529-ead674c2-d6da-4e9f-8d3d-a14a093ed8cc.jpg)

**Comment by HugoPerard** [comment]
This bug was fix with absent feature release
