### ISSUE TITLE
Add avatars on the "Bureaux" page

### ISSUE THREAD

**Issue by yoannfleurydev** [HugoPerard/standup-app#32]
**Is your feature request related to a problem? Please describe.**

On the "Bureaux" page, there are only names. It could be great to also have people faces in the badge.

**Describe the solution you'd like**

Like the "Remerciements" page, an avatar of the people can improve the readability of who is there or not.

![image](https://user-images.githubusercontent.com/3920615/135827145-22048fa4-4fdf-4464-b6d9-88b52a61dd19.png)

**Comment by jakubkopco** [comment]
Hi can I get this issue please?

**Comment by HugoPerard** [comment]
Of course, and if you have question, ask here 🙂

**Comment by HugoPerard** [comment]
You can add me on Discord : Drarep#6058

**Comment by jakubkopco** [comment]
i sent u friend request :)

**Comment by jakubkopco** [comment]
@HugoPerard @yoannfleurydev please, can you check PR? :)
