### ISSUE TITLE
Double ScrollView on the "standup" page

### ISSUE THREAD

**Issue by emmanuel-bearstudio** [HugoPerard/standup-app#33]
**Describe the bug**
On the page "standup" (where there is the projet scroll), there is a bug where i can scroll from two scroll view. One from the project scrollview and which is smaller that makes me go through an infinite scroll. 

**To Reproduce**
1. Go to the "standup" page
2. Either you can put your cursor at the bottom of the page and scroll with your mouse pad from left to right 
3. Or you can use the directional arrows 

**Expected behavior**
You should have only one scrollview

**Screenshots**

https://user-images.githubusercontent.com/62236130/136001757-6c419443-e42c-4dc7-954e-d3890a4b402a.mov

**Comment by HugoPerard** [comment]
With Stand-Up page layout change, this issue is no longer relevant
