### ISSUE TITLE
Project name edition

### ISSUE THREAD

**Issue by HugoPerard** [HugoPerard/standup-app#4]
**Is your feature request related to a problem? Please describe.**
There is no way to rename a project.

**Describe the solution you'd like**
Permit project edition to rename it

**Comment by yoannfleurydev** [comment]
I am taking this one, I want to learn a bit more about the update using Firebase, I'll do it this week if I find the time.

![bitmoji](https://sdk.bitmoji.com/render/panel/e0025372-cccf-45e4-8ab4-3abd16875933-28509fbe-5dd0-4c1e-9b9f-5043673dc433-v1.png?transparent=1&palette=1&width=246)
