### ISSUE TITLE
The "Editer" button on "Objectifs" screen does not work

### ISSUE THREAD

**Issue by ivan-dalmet** [HugoPerard/standup-app#8]
**Describe the bug**
When I try to edit an objective, it doesn't work

![image](https://user-images.githubusercontent.com/9749061/125431669-a200b4de-6375-4bdd-bb91-4a3203db777c.png)

**To Reproduce**
1. Go to 'https://standup-app.vercel.app/app/objectifs'
2. Connect with a BearStudio account
3. Try to edit an objective
5. Nothing append 😢

**Comment by HugoPerard** [comment]
This feature is available since today and #9. This issue will be close in few days when the feature will be tested

**Comment by yoannfleurydev** [comment]
This bug fix looks good to me on production, we can probably close this issue.
